import type { CityConfig } from './contracts';

const mk = (cityKey: string, displayName: string, seriesSlug: string): CityConfig => ({
  cityKey,
  displayName,
  seriesSlug,
  airportCode: null,
  timezone: null,
  enabled: true,
  resolutionSourceOverride: null,
});

export const DEFAULT_CITY_CONFIGS: CityConfig[] = [
  mk('amsterdam', 'Amsterdam', 'amsterdam-daily-weather'),
  mk('ankara', 'Ankara', 'ankara-daily-weather'),
  mk('atlanta', 'Atlanta', 'atlanta-daily-weather'),
  mk('austin', 'Austin', 'austin-daily-weather'),
  mk('beijing', 'Beijing', 'beijing-daily-weather'),
  mk('buenos-aires', 'Buenos Aires', 'buenos-aires-daily-weather'),
  mk('busan', 'Busan', 'busan-daily-weather'),
  mk('cape-town', 'Cape Town', 'cape-town-daily-weather'),
  mk('chengdu', 'Chengdu', 'chengdu-daily-weather'),
  mk('chicago', 'Chicago', 'chicago-daily-weather'),
  mk('chongqing', 'Chongqing', 'chongqing-daily-weather'),
  mk('dallas', 'Dallas', 'dallas-daily-weather'),
  mk('denver', 'Denver', 'denver-daily-weather'),
  mk('helsinki', 'Helsinki', 'helsinki-daily-weather'),
  mk('hong-kong', 'Hong Kong', 'hong-kong-daily-weather'),
  mk('houston', 'Houston', 'houston-daily-weather'),
  mk('istanbul', 'Istanbul', 'istanbul-daily-weather'),
  mk('jakarta', 'Jakarta', 'jakarta-daily-weather'),
  mk('jeddah', 'Jeddah', 'jeddah-daily-weather'),
  mk('kuala-lumpur', 'Kuala Lumpur', 'kuala-lumpur-daily-weather'),
  mk('lagos', 'Lagos', 'lagos-daily-weather'),
  mk('london', 'London', 'london-daily-weather'),
  mk('los-angeles', 'Los Angeles', 'los-angeles-daily-weather'),
  mk('lucknow', 'Lucknow', 'lucknow-daily-weather'),
  mk('madrid', 'Madrid', 'madrid-daily-weather'),
  mk('mexico-city', 'Mexico City', 'mexico-city-daily-weather'),
  mk('miami', 'Miami', 'miami-daily-weather'),
  mk('milan', 'Milan', 'milan-daily-weather'),
  mk('moscow', 'Moscow', 'moscow-daily-weather'),
  mk('munich', 'Munich', 'munich-daily-weather'),
  mk('nyc', 'New York City', 'nyc-daily-weather'),
  mk('panama-city', 'Panama City', 'panama-daily-weather'),
  mk('paris', 'Paris', 'paris-daily-weather'),
  mk('san-francisco', 'San Francisco', 'san-francisco-daily-weather'),
  mk('sao-paulo', 'Sao Paulo', 'sao-paulo-daily-weather'),
  mk('seattle', 'Seattle', 'seattle-daily-weather'),
  mk('seoul', 'Seoul', 'seoul-daily-weather'),
  mk('shanghai', 'Shanghai', 'shanghai-daily-weather'),
  mk('shenzhen', 'Shenzhen', 'shenzhen-daily-weather'),
  mk('singapore', 'Singapore', 'singapore-daily-weather'),
  mk('taipei', 'Taipei', 'taipei-daily-weather'),
  mk('tel-aviv', 'Tel Aviv', 'tel-aviv-daily-weather'),
  mk('tokyo', 'Tokyo', 'tokyo-daily-weather'),
  mk('toronto', 'Toronto', 'toronto-daily-weather'),
  mk('warsaw', 'Warsaw', 'warsaw-daily-weather'),
  mk('wellington', 'Wellington', 'wellington-daily-weather'),
  mk('wuhan', 'Wuhan', 'wuhan-daily-weather'),
];
